AWSTemplateFormatVersion: 2010-09-09
Description : Get metadata from an mp4 file using ffprobe

Parameters:
 FFprobeCodeKey:
   Description: The s3 key where the FFprobe code can be found
   Type: String

 OMDbPostersCodeKey:
   Description: The s3 key where the OMDbPosters code can be found
   Type: String

 OMDbCodeKey:
   Description: The s3 key where the OMDb code can be found
   Type: String

 KodiSTRMCodeKey:
   Description: The s3 key where the KodiSTRM code can be found
   Type: String

 KodiNFOCodeKey:
   Description: The s3 key where the KodiNFO code can be found
   Type: String

 PosterCodeKey:
   Description: The s3 key where the KodiNFO code can be found
   Type: String

Resources:
  FFprobeLambda:
    Type : AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !ImportValue s3strm-settings-bucket
        S3Key: !Ref FFprobeCodeKey
      Description: Get the metadata from an mp4 file using ffprobe
      FunctionName: s3strm-ffprobe
      Handler: ffprobe.lambda_handler
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Runtime: python2.7
      Timeout: 120
    DependsOn: Role

  OMDbPostersLambda:
    Type : AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !ImportValue s3strm-settings-bucket
        S3Key: !Ref OMDbPostersCodeKey
      Environment:
        Variables:
          OMDB_API_KEY: !ImportValue s3strm-omdb-api-key
          POSTER_HEIGHT: 900
          MOVIES_BUCKET: !ImportValue s3strm-movies-bucket
      Description : Get the posters from the OMDB API
      FunctionName : s3strm-omdb-posters
      Handler : poster.lambda_handler
      MemorySize : 128
      Role : !GetAtt Role.Arn
      Runtime : python2.7
      Timeout : 120
    DependsOn: Role

  OMDbLambda:
    Type : AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !ImportValue s3strm-settings-bucket
        S3Key: !Ref OMDbCodeKey
      Environment:
        Variables:
          MOVIES_BUCKET: !ImportValue s3strm-movies-bucket
          OMDB_API_KEY: !ImportValue s3strm-omdb-api-key
      Description : Generate a omdb.json file
      FunctionName : s3strm-omdb
      Handler : omdb.lambda_handler
      MemorySize : 128
      Role : !GetAtt Role.Arn
      Runtime : python2.7
      Timeout : 120
    DependsOn: Role

  KodiSTRMLambda:
    Type : AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !ImportValue s3strm-settings-bucket
        S3Key: !Ref KodiSTRMCodeKey
      Environment:
        Variables:
          MOVIES_BUCKET: !ImportValue s3strm-movies-bucket
          API_GATEWAY_DOMAIN: !ImportValue s3strm-api-gateway-domain
          API_KEY: !ImportValue s3strm-api-key
      Description : Generate a kodi.strm file
      FunctionName : s3strm-kodi-strm
      Handler : strm.lambda_handler
      MemorySize : 128
      Role : !GetAtt Role.Arn
      Runtime : python2.7
      Timeout : 120
    DependsOn: Role

  KodiNFOLambda:
    Type : AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !ImportValue s3strm-settings-bucket
        S3Key: !Ref KodiNFOCodeKey
      Environment:
        Variables:
          MOVIES_BUCKET: !ImportValue s3strm-movies-bucket
          MOVIES_BUCKET_REGION: !Ref AWS::Region
      Description : Generate a kodi.nfo file
      FunctionName : s3strm-kodi-nfo
      Handler : nfo.lambda_handler
      MemorySize : 128
      Role : !GetAtt Role.Arn
      Runtime : python2.7
      Timeout : 120
    DependsOn: Role

  PosterLambda:
    Type : AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !ImportValue s3strm-settings-bucket
        S3Key: !Ref PosterCodeKey
      Environment:
        Variables:
          MOVIES_BUCKET: !ImportValue s3strm-movies-bucket
      Description : Generate a poster.jpg file with the best available art
      FunctionName : s3strm-poster
      Handler : lambda.lambda_handler
      MemorySize : 128
      Role : !GetAtt Role.Arn
      Runtime : python2.7
      Timeout : 20
    DependsOn: Role

  FFprobeInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Join [ ":", [ "arn:aws:sns", Ref: "AWS::Region", Ref: "AWS::AccountId", "*" ] ]
      FunctionName: !GetAtt FFprobeLambda.Arn

  OMDbPostersInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Join [ ":", [ "arn:aws:sns", Ref: "AWS::Region", Ref: "AWS::AccountId", "*" ] ]
      FunctionName: !GetAtt OMDbPostersLambda.Arn

  OMDbInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Join [ ":", [ "arn:aws:sns", Ref: "AWS::Region", Ref: "AWS::AccountId", "*" ] ]
      FunctionName: !GetAtt OMDbLambda.Arn

  KodiSTRMInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Join [ ":", [ "arn:aws:sns", Ref: "AWS::Region", Ref: "AWS::AccountId", "*" ] ]
      FunctionName: !GetAtt KodiSTRMLambda.Arn

  KodiNFOInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Join [ ":", [ "arn:aws:sns", Ref: "AWS::Region", Ref: "AWS::AccountId", "*" ] ]
      FunctionName: !GetAtt KodiNFOLambda.Arn

  PosterInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Join [ ":", [ "arn:aws:sns", Ref: "AWS::Region", Ref: "AWS::AccountId", "*" ] ]
      FunctionName: !GetAtt PosterLambda.Arn

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version : 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "s3strm-movie-processor"
          PolicyDocument:
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
              -
                Effect: Allow
                Action: "s3:*"
                Resource: !Join [ "", [ "arn:aws:s3:::", !ImportValue s3strm-movies-bucket, "/*" ] ]
              -
                Effect: Allow
                Action: "s3:*"
                Resource: !Join [ "", [ "arn:aws:s3:::", !ImportValue s3strm-settings-bucket, "/*" ] ]

  FFprobeSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt FFprobeLambda.Arn
      Protocol: "lambda"
      TopicArn: !ImportValue s3strm-video-created-topic

  OMDbPostersSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt OMDbPostersLambda.Arn
      Protocol: "lambda"
      TopicArn: !ImportValue s3strm-video-created-topic

  OMDbSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt OMDbLambda.Arn
      Protocol: "lambda"
      TopicArn: !ImportValue s3strm-video-created-topic

  KodiSTRMSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt KodiSTRMLambda.Arn
      Protocol: "lambda"
      TopicArn: !ImportValue s3strm-meta-created-topic

  KodiNFOSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt KodiNFOLambda.Arn
      Protocol: "lambda"
      TopicArn: !ImportValue s3strm-meta-created-topic

  PosterSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt PosterLambda.Arn
      Protocol: "lambda"
      TopicArn: !ImportValue s3strm-poster-created-topic

Outputs:
  FFprobeLambdaArn:
    Value: !GetAtt FFprobeLambda.Arn

  OMDbPostersLambdaArn:
    Value: !GetAtt OMDbPostersLambda.Arn

  OMDbLambdaArn:
    Value: !GetAtt OMDbLambda.Arn

  KodiSTRMLambdaArn:
    Value: !GetAtt KodiSTRMLambda.Arn

  KodiNFOLambdaArn:
    Value: !GetAtt KodiNFOLambda.Arn

  PosterLambdaArn:
    Value: !GetAtt PosterLambda.Arn
